import discord
from discord.ext import commands
from discord import app_commands
import os
import csv
from datetime import datetime, timedelta

TOKEN = "COLE_SEU_TOKEN_AQUI"
GUILD_ID = SEU_GUILD_ID_AQUI  # Substitua pelo ID do seu servidor
JOGADOR_ROLE_NAME = "Jogador"

intents = discord.Intents.default()
intents.message_content = True
intents.members = True
intents.voice_states = True
intents.guilds = True
intents.presences = True
intents.messages = True

bot = commands.Bot(command_prefix="/", intents=intents)

REGISTROS_FILE = "registros.csv"
IMAGENS_DIR = "imagens"
os.makedirs(IMAGENS_DIR, exist_ok=True)

# Inicializa CSV se não existir
if not os.path.exists(REGISTROS_FILE):
    with open(REGISTROS_FILE, "w", newline="") as f:
            writer = csv.writer(f)
                    writer.writerow(["user_id", "username", "data", "hora_entrada", "hora_saida", "entrada_img", "saida_img"])


                    def salvar_registro(user_id, username, data, entrada=None, saida=None, entrada_img=None, saida_img=None):
                        registros = []
                            atualizado = False
                                with open(REGISTROS_FILE, "r", newline="") as f:
                                        reader = csv.reader(f)
                                                headers = next(reader)
                                                        for row in reader:
                                                                    if row[0] == user_id and row[2] == data:
                                                                                    if entrada:
                                                                                                        row[3] = entrada
                                                                                                                        if saida:
                                                                                                                                            row[4] = saida
                                                                                                                                                            if entrada_img:
                                                                                                                                                                                row[5] = entrada_img
                                                                                                                                                                                                if saida_img:
                                                                                                                                                                                                                    row[6] = saida_img
                                                                                                                                                                                                                                    atualizado = True
                                                                                                                                                                                                                                                registros.append(row)

                                                                                                                                                                                                                                                    if not atualizado:
                                                                                                                                                                                                                                                            registros.append([user_id, username, data, entrada or "", saida or "", entrada_img or "", saida_img or ""])

                                                                                                                                                                                                                                                                with open(REGISTROS_FILE, "w", newline="") as f:
                                                                                                                                                                                                                                                                        writer = csv.writer(f)
                                                                                                                                                                                                                                                                                writer.writerow(headers)
                                                                                                                                                                                                                                                                                        writer.writerows(registros)


                                                                                                                                                                                                                                                                                        def calcular_media(user_id):
                                                                                                                                                                                                                                                                                            total = timedelta()
                                                                                                                                                                                                                                                                                                dias = set()
                                                                                                                                                                                                                                                                                                    with open(REGISTROS_FILE, "r") as f:
                                                                                                                                                                                                                                                                                                            reader = csv.DictReader(f)
                                                                                                                                                                                                                                                                                                                    for row in reader:
                                                                                                                                                                                                                                                                                                                                if row["user_id"] == user_id and row["hora_entrada"] and row["hora_saida"]:
                                                                                                                                                                                                                                                                                                                                                dias.add(row["data"])
                                                                                                                                                                                                                                                                                                                                                                fmt = "%H:%M:%S"
                                                                                                                                                                                                                                                                                                                                                                                entrada = datetime.strptime(row["hora_entrada"], fmt)
                                                                                                                                                                                                                                                                                                                                                                                                saida = datetime.strptime(row["hora_saida"], fmt)
                                                                                                                                                                                                                                                                                                                                                                                                                total += (saida - entrada)
                                                                                                                                                                                                                                                                                                                                                                                                                    if len(dias) == 0:
                                                                                                                                                                                                                                                                                                                                                                                                                            return "0h"
                                                                                                                                                                                                                                                                                                                                                                                                                                media = total / len(dias)
                                                                                                                                                                                                                                                                                                                                                                                                                                    return str(media).split(".")[0]  # Remove microssegundos


                                                                                                                                                                                                                                                                                                                                                                                                                                    @bot.event
                                                                                                                                                                                                                                                                                                                                                                                                                                    async def on_ready():
                                                                                                                                                                                                                                                                                                                                                                                                                                        await bot.tree.sync(guild=discord.Object(id=GUILD_ID))
                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"Bot conectado como {bot.user}")


                                                                                                                                                                                                                                                                                                                                                                                                                                            @bot.tree.command(name="entrada", description="Registrar entrada com foto", guild=discord.Object(id=GUILD_ID))
                                                                                                                                                                                                                                                                                                                                                                                                                                            @app_commands.describe(foto="Envie uma foto tirada agora")
                                                                                                                                                                                                                                                                                                                                                                                                                                            async def entrada(interaction: discord.Interaction, foto: discord.Attachment):
                                                                                                                                                                                                                                                                                                                                                                                                                                                role_names = [role.name for role in interaction.user.roles]
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if JOGADOR_ROLE_NAME not in role_names:
                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.response.send_message("Você não tem permissão para isso.", ephemeral=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        agora = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data = agora.strftime("%Y-%m-%d")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                hora = agora.strftime("%H:%M:%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    filename = f"{interaction.user.id}_{data}_entrada.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        caminho = os.path.join(IMAGENS_DIR, filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await foto.save(caminho)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                salvar_registro(str(interaction.user.id), interaction.user.name, data, entrada=hora, entrada_img=filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await interaction.response.send_message(f"Entrada registrada às {hora} com foto.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @bot.tree.command(name="saida", description="Registrar saída com foto", guild=discord.Object(id=GUILD_ID))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app_commands.describe(foto="Envie uma foto tirada agora")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    async def saida(interaction: discord.Interaction, foto: discord.Attachment):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        role_names = [role.name for role in interaction.user.roles]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if JOGADOR_ROLE_NAME not in role_names:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await interaction.response.send_message("Você não tem permissão para isso.", ephemeral=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                agora = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data = agora.strftime("%Y-%m-%d")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        hora = agora.strftime("%H:%M:%S")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            filename = f"{interaction.user.id}_{data}_saida.png"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                caminho = os.path.join(IMAGENS_DIR, filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await foto.save(caminho)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        salvar_registro(str(interaction.user.id), interaction.user.name, data, saida=hora, saida_img=filename)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await interaction.response.send_message(f"Saída registrada às {hora} com foto.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            @bot.tree.command(name="presenca", description="Mostra seu registro de hoje", guild=discord.Object(id=GUILD_ID))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async def presenca(interaction: discord.Interaction):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                agora = datetime.now()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data = agora.strftime("%Y-%m-%d")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(REGISTROS_FILE, "r") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reader = csv.DictReader(f)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for row in reader:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if row["user_id"] == str(interaction.user.id) and row["data"] == data:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    msg = f"**{interaction.user.name}** em {data}\nEntrada: {row['hora_entrada']}\nSaída: {row['hora_saida']}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await interaction.response.send_message(msg)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await interaction.response.send_message("Você ainda não tem registro hoje.")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @bot.tree.command(name="resumo", description="Média de horas da semana", guild=discord.Object(id=GUILD_ID))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        async def resumo(interaction: discord.Interaction):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            media = calcular_media(str(interaction.user.id))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await interaction.response.send_message(f"Sua média de horas por dia (semana): {media}")


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                bot.run(TOKEN)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                